CREATE TABLE account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- HSQLDB自增主键标准语法
    account_name VARCHAR(50),
password VARCHAR(50),
email VARCHAR(100) NOT NULL,
account_status INT NOT NULL,
create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uk_email UNIQUE (email)
);

-- 添加表注释（HSQLDB表注释需单独执行）
COMMENT ON TABLE account IS '账户表';

-- 添加列注释（HSQLDB列注释需单独执行）
COMMENT ON COLUMN account.account_id IS '账户ID';
COMMENT ON COLUMN account.account_name IS '账户名称';
COMMENT ON COLUMN account.password IS '账户密码';
COMMENT ON COLUMN account.email IS '账户email';
COMMENT ON COLUMN account.account_status IS '账户状态：0-正常 1-冻结 2-注销';
COMMENT ON COLUMN account.create_time IS '账户创建时间';
COMMENT ON COLUMN account.update_time IS '账户更新时间';

-- 创建复合索引（HSQLDB索引需单独创建）
CREATE INDEX idx_email_accountname ON account (email, account_name);