server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:XlForum}
#  datasource:
#    url: jdbc:mysql://localhost:3306/xlforum
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP配置:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    # 关键参数说明：
    # MODE=MySQL：启用 MySQL 兼容模式
    # DATABASE_TO_LOWER=TRUE：表名、列名大小写不敏感（匹配 MySQL 默认行为）
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  h2:
    console:
      enabled: true  # 启用 H2 Web 控制台（测试时可可视化查看数据）
      path: /h2-console  # 控制台访问路径（浏览器打开 http://localhost:8080/h2-console）
  jpa:
    hibernate:
      ddl-auto: none  # 禁用自动创建/修改表，改为手动管理
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  # Mapper.xml文件的位置（默认扫描resources目录下的mappers文件夹）
  mapper-locations: classpath:mappers/*.xml
  # 实体类的包路径（配置后，Mapper.xml中可直接用类名简称，无需全类名）
  type-aliases-package: com.zxl.xlforum.*.entity
  # 开启驼峰命名映射（如数据库字段user_name -> 实体类属性userName）
  configuration:
    map-underscore-to-camel-case: true